Update ci.yaml
Signed-off-by: thepetk <thepetk@gmail.com>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -28,24 +28,27 @@ jobs:
       - name: Build binary
         run: make build
 
+      - name: Run Go tests
+        run: |
+          go test ./... -coverprofile coverage.out -covermode count
+          go tool cover -func coverage.out
+
       - name: Check test coverage
         env:
             TESTCOVERAGE_THRESHOLD: 80
         run: |
-              echo "Quality Gate: checking test coverage is above threshold ..."
-              echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
-              totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-              echo "Current test coverage : $totalCoverage %"
-              if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-                  echo "OK"
-              else
-                  echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-                  echo "Failed"
-                  exit 1
-              fi
+          echo "Checking if coverage is above threshold..."
+          echo "Coverage Threshold: $TESTCOVERAGE_THRESHOLD %"
+          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "OK"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Failed"
+              exit 1
+          fi
 
-      - name: Run Go tests
-        run: make test
 
       - name: Run Gosec Security Scanner
         run: |
